# Generated by Django 6.0.3 on 2026-07-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_site_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictofficer',
            name='assigned_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ict_officers', to='monitoring.region'),
        ),
    ]
