# Generated by Django 6.0.3 on 2026-07-15 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_ictofficer_assigned_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinghistory',
            name='logged_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='pinghistory',
            index=models.Index(fields=['site'], name='monitoring__site_id_abfd86_idx'),
        ),
        migrations.AddIndex(
            model_name='pinghistory',
            index=models.Index(fields=['logged_at'], name='monitoring__logged__365a9c_idx'),
        ),
    ]
