# Generated by Django 6.0.3 on 2026-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_pinghistory_logged_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='ip_address',
            new_name='device_ip_address',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_code',
        ),
        migrations.AddField(
            model_name='site',
            name='networkdevice',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
